/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/models/cloud/model.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/model.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Node.geometry}
        material={materials["lambert2SG.001"]}
      />
    </group>
  );
}

useGLTF.preload("/model.glb");
